//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracDisDonanim
    {
        public int ID { get; set; }
        public Nullable<int> IDArac { get; set; }
        public Nullable<bool> FarLed { get; set; }
        public Nullable<bool> FarSis { get; set; }
        public Nullable<bool> Sunroof { get; set; }
        public Nullable<bool> ElektrikliAyna { get; set; }
        public Nullable<bool> ParkSensoru { get; set; }
        public Nullable<bool> OtomatikKatlananAyna { get; set; }
        public Nullable<bool> RomorkDemiri { get; set; }
        public Nullable<bool> ParkAsistani { get; set; }
    }
}
