//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracIcDonanım
    {
        public int ID { get; set; }
        public Nullable<int> IDArac { get; set; }
        public Nullable<bool> DeriKoltuk { get; set; }
        public Nullable<bool> SogutmaliKoltuk { get; set; }
        public Nullable<bool> YolBilgisayarı { get; set; }
        public Nullable<bool> KumasKoltuk { get; set; }
        public Nullable<bool> Klima { get; set; }
        public Nullable<bool> HidrolikDireksiyon { get; set; }
        public Nullable<bool> HizSabitleyici { get; set; }
        public Nullable<bool> GeriGorusKamera { get; set; }
    }
}
