//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracGuvenlik
    {
        public int ID { get; set; }
        public Nullable<int> IDArac { get; set; }
        public Nullable<bool> ABS { get; set; }
        public Nullable<bool> YokusDestegi { get; set; }
        public Nullable<bool> HavaYastigi { get; set; }
        public Nullable<bool> CocukKilidi { get; set; }
    }
}
