//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilanlar
    {
        public int ID { get; set; }
        public Nullable<int> IDMarka { get; set; }
        public Nullable<int> IDModel { get; set; }
        public Nullable<int> IDMusteri { get; set; }
        public string Fiyat { get; set; }
        public string Kilometre { get; set; }
        public Nullable<System.DateTime> Yil { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public string Kasa { get; set; }
        public string MotorGucu { get; set; }
        public string MotorHacmi { get; set; }
        public string Cekis { get; set; }
        public Nullable<System.DateTime> IlanTarihi { get; set; }
    }
}
