//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaEntities : DbContext
    {
        public AracKiralamaEntities()
            : base("name=AracKiralamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AracDisDonanim> AracDisDonanim { get; set; }
        public virtual DbSet<AracGuvenlik> AracGuvenlik { get; set; }
        public virtual DbSet<AracIcDonanım> AracIcDonanım { get; set; }
        public virtual DbSet<AracMarka> AracMarka { get; set; }
        public virtual DbSet<Ilanlar> Ilanlar { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
    }
}
